[package]
name = "pcupback"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", features = ["password-hash"] }
chrono = "0.4"
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", features = ["sqlx_sqlite"] }
serde = "1.0.218"
sqlx = "0.7" # rocket_db_pools requires sqlx 0.7
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.15", features = ["v4"] }

[profile.release]
lto = "fat"
codegen-units = 1
